[package]
name = "vec-map"
version = "0.3.1"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2021"
publish = false

[features]
default = ["rayon"]

[dependencies]
rayon = { version = "1", optional = true }
serde = { version = "1", optional = true }

[dev-dependencies]
rayon = "1"
