[package]
name = "vec-map"
version = "0.1.5-alpha.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2018"
publish = false

[features]
default = ["rayon"]

[dependencies]
rayon = { version = "1", optional = true }
